name: "Check Code"

on:
  pull_request:
    branches:
      - main

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # 4.0.0
        with:
          go-version: 1.20.2

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -ldflags "-s -w --extldflags '-static -fpic'" -o ./bin/sesmate ./cmd/sesmate
        env:
            CGO_ENABLED: 0
