name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  github:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # 4.0.0
        with:
          go-version: 1.20.2

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: |
          for i in $(echo $LIST | tr ',' ' ')
          do
          export GOOS=`echo $i | cut -d'/' -f1`
          export GOARCH=`echo $i | cut -d'/' -f2`

          if [ "$GOOS" = "windows" ]; then
            export FILENAME=sesmate-$GOOS-$GOARCH.exe
          else
            export FILENAME=sesmate-$GOOS-$GOARCH
          fi

          go build -ldflags "-s -w --extldflags '-static -fpic'" -o ./bin/$FILENAME ./cmd/sesmate
          echo "Build sesmate-$GOOS-$GOARCH done"

          done
        env:
          CGO_ENABLED: 0
          LIST: linux/amd64,linux/arm64,windows/amd64,windows/arm64,darwin/amd64,darwin/arm64

      - name: Create github release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          files: bin/sesmate-*
          generate_release_notes: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # 4.0.0
        with:
          context: .
          push: true
          tags: blackhole007/sesmate:latest,blackhole007/sesmate:${{ github.ref_name }}
